name: .NET Core

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build Solution
      run: dotnet build --configuration Release --no-restore
    - name: Run Sample
      run: dotnet run -c Release --project ./samples/Svg.Skia.SourceGenerator.Sample/Svg.Skia.SourceGenerator.Sample.csproj
    - name: Pack NuGet
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Publish AvaloniaSample
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      run: dotnet publish ./samples/AvaloniaSample/AvaloniaSample.csproj -c Release -f netcoreapp3.1 -r win7-x64 /p:PublishTrimmed=True /p:PublishSingleFile=False /p:PublishReadyToRun=True -o ./artifacts/AvaloniaSample-win7-x64
    - name: Publish svgc
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      run: dotnet publish ./src/svgc/svgc.csproj -c Release -f netcoreapp3.1 -r win7-x64 /p:PublishTrimmed=True /p:PublishSingleFile=False /p:PublishReadyToRun=True -o ./artifacts/svgc-win7-x64
    - name: Artifacts NuGet
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: NuGet
        path: ./artifacts/NuGet/*.nupkg
    - name: Artifacts AvaloniaSample
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: AvaloniaSample-win7-x64
        path: ./artifacts/AvaloniaSample-win7-x64
    - name: Artifacts svgc
      if: github.event_name != 'pull_request' && matrix.os == 'windows-latest'
      uses: actions/upload-artifact@master
      with:
        name: svgc-win7-x64
        path: ./artifacts/svgc-win7-x64
